http:
  routers:
    traefik-dashboard:
      entryPoints:
        - websecure
      rule: Host(`traefik-dashboard.neukoch.com`)
      middlewares:
        - traefik-auth
      tls:
        certResolver: cloudflare
      service: api@internal