name: home-infrastructure-databases
services:
  postgres:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/infrastructure/postgres/data:/var/lib/postgresql/data
      - ./init-scripts/databases/postgres/init.paperless.sh:/docker-entrypoint-initdb.d/init.paperless.sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PAPERLESS_POSTGRES_DATABASE: ${PAPERLESS_POSTGRES_DATABASE}
      PAPERLESS_POSTGRES_USER: ${PAPERLESS_POSTGRES_USER}
      PAPERLESS_POSTGRES_PASSWORD: ${PAPERLESS_POSTGRES_PASSWORD}
    ports: 
      - 5432:5432

networks:
  postgres: