name: home.infrastructure.databases
services:
  postgres:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/infrastructure/postgres/data:/var/lib/postgresql/data
      - ./init-scripts/databases/postgres.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_ADMIN_USER: ${INFRASTRUCTURE_POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${INFRASTRUCTURE_POSTGRES_ADMIN_PASSWORD}
      DATABASES: |
        ${PAPERLESS_POSTGRES_DATABASE}
      USERS: |
        ${PAPERLESS_POSTGRES_USER}
      PASSWORDS: |
        ${PAPERLESS_POSTGRES_PASSWORD}

networks:
  postgres: