services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.1.3:
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    labels:
      traefik.enable: true
      traefik.http.routers.paperless.rule: Host(`paperless.neukoch.com`)
      traefik.http.services.paperless.loadbalancer.server.port: 8080