services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.1.3
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - mqtt
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.zigbee2mqtt.rule: Host(`zigbee2mqtt.neukoch.com`)
      traefik.http.services.zigbee2mqtt.loadbalancer.server.port: 8080
networks:
  mqtt:
    external: true
  proxy:
    external: true