services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.21
    restart: unless-stopped
    volumes:
      - "${CONTAINER_DATA_DIRECTORY}/mosquitto:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

networks:
  mosquitto: