services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.21
    restart: unless-stopped
    volumes:
      - "${CONTAINER_DATA_DIRECTORY}/mosquitto:/mosquitto"
    ports:
      - "1883:1883"
    labels:
      traefik.enable: true
      traefik.tcp.routers.mosquitto.rule: HostSNI(`mosquitto.neukoch.com`)
      traefik.http.routers.mosquitto.entrypoint: mqttsecure
      traefik.http.services.portainer.loadbalancer.server.port: 1883


networks:
  mosquitto:
  proxy:
    external: true 