name: home_services_documents
services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless-ngx_redis
      - paperless-ngx_postgres
    ports:
      - "8000:8000"
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/documents/paperless-ngx/data:/usr/src/paperless/data
      - ${CONTAINER_DATA_DIRECTORY}/documents/paperless-ngx/media:/usr/src/paperless/media
    environment:
      PAPERLESS_REDIS: redis://paperless-ngx_redis:6379
      PAPERLESS_DBHOST: paperless-ngx_postgres

  paperless-ngx_redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/documents/paperless-ngx_redis/data:/data

  paperless-ngx_postgres:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/documents/paperless-ngx_postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless