global:
  sendAnonymousUsage: false

log:
  level: DEBUG

accessLog: {}

api: 
  dashboard: true
  insecure: false
  debug: true

entryPoints:
  web:
    address: :80
    http: 
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  cloudflare-prod:
    acme:
      storage: /etc/traefik/certs/cloudflare-acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      keyType: EC256
      dnsChallenge: 
        provider: cloudflare
        resolvers: 
          - 1.1.1.1:83
          - 8.8.8.8:83
  cloudflare-staging:
    acme:
      storage: /etc/traefik/certs/cloudflare-acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      keyType: EC256
      dnsChallenge: 
        provider: cloudflare
        resolvers: 
          - 1.1.1.1:83
          - 8.8.8.8:83

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik/conf/
    watch: true