services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless-ngx_redis
      - paperless-ngx_postgres
    ports:
      - 8000:8000
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/paperless-ngx/data:/usr/src/paperless/data
      - ${CONTAINER_DATA_DIRECTORY}/paperless-ngx/media:/usr/src/paperless/media
    environment:
      PAPERLESS_REDIS: redis://paperless-ngx_redis:6379
      PAPERLESS_DBHOST: paperless-ngx_postgres
      PAPERLESS_DBNAME: ${SERVICES_PAPERLESS_POSTGRES_DATABASENAME}
      PAPERLESS_DBUSER: ${SERVICES_PAPERLESS_POSTGRES_USERNAME}
      PAPERLESS_DBPASS: ${SERVICES_PAPERLESS_POSTGRES_PASSWORD}
      PAPERLESS_ADMIN_USER: ${SERVICES_PAPERLESS_ADMIN_USERNAME}
      PAPERLESS_ADMIN_PASSWORD: ${SERVICES_PAPERLESS_ADMIN_PASSWORD}

  paperless-ngx_redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/documents/paperless-ngx_redis/data:/data

  paperless-ngx_postgres:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/documents/paperless-ngx_postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SERVICES_PAPERLESS_POSTGRES_DATABASENAME}
      POSTGRES_USER: ${SERVICES_PAPERLESS_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${SERVICES_PAPERLESS_POSTGRES_PASSWORD}