services:
  app:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/hortusfox-web/app/logs:/var/www/html/app/logs
      - ${CONTAINER_DATA_DIRECTORY}/hortusfox-web/app/migrations:/var/www/html/app/migrations
      - ${CONTAINER_DATA_DIRECTORY}/hortusfox-web/public/img:/var/www/html/public/img
      - ${CONTAINER_DATA_DIRECTORY}/hortusfox-web/public/backup:/var/www/html/public/backup
      - ${CONTAINER_DATA_DIRECTORY}/hortusfox-web/public/themes:/var/www/html/public/themes
    environment:
      APP_ADMIN_EMAIL: ${ADMIN_EMAIL}
      APP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      APP_TIMEZONE: "MET"
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: ${DATABASE_DATABASENAME}
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_CHARSET: "utf8mb4"
    depends_on:
      - database
    networks:
      - proxy
      - hortusfox
    labels:
      traefik.enable: true
      traefik.http.routers.hortusfox.rule: Host(`hortusfox.neukoch.com`)
      traefik.http.services.hortusfox.loadbalancer.server.port: 80

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOTPASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASENAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${CONTAINER_DATA_DIRECTORY}/hortusfox-web/mariadb/mysql:/var/lib/mysql
    networks:
      - hortusfox

networks:
  hortusfox:
  proxy:
    external: true