services:
  traefik:
    container_name: traefik
    image: traefik:3.3.4
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/conf/:/etc/traefik/conf/:ro
      - ${CONTAINER_DATA_DIRECTORY}/traefik/certs:/etc/traefik/certs/:rw
    environment:
      CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      DASHBOARD_CREDENTIALS: 
    labels:
      traefik.enable: true
      traefik.certificatesresolvers.cloudflare-prod.acme.email: ${CLOUDFLARE_EMAIL}
      traefik.certificatesresolvers.cloudflare-staging.acme.email: ${CLOUDFLARE_EMAIL}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy: 