services:
  traefik:
    container_name: traefik
    image: traefik:3.3.4
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8883:8883
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONTAINER_DATA_DIRECTORY}/traefik/certs:/etc/traefik/certs/:rw
    environment:
      CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
      TRAEFIK_LOG_LEVEL: ${LOG_LEVEL:-ERROR}
      TRAEFIK_API_DASHBOARD: true

      # HTTP 
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: :443
      TRAEFIK_ENTRYPOINTS_HTTPS_ASDEFAULT: true
      TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_TLS_CERTRESOLVER: cloudflare

      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: :80
      TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_TO: websecure
      TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: https
      TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_PERMANENT: true

      # MQTT
      TRAEFIK_ENTRYPOINTS_MQTTS_ADDRESS: :8883
      TRAEFIK_ENTRYPOINTS_MQTTS_HTTP_TLS_ASDEFAULT: true
      TRAEFIK_ENTRYPOINTS_MQTTS_HTTP_TLS_CERTRESOLVER: cloudflare

      # Certificates
      TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_EMAIL: ${CLOUDFLARE_EMAIL}
      TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_STORAGE: /etc/traefik/certs/cloudflare-acme.json
      TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_CASERVER: https://acme-v02.api.letsencrypt.org/directory
      TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_DNSCHALLENGE_PROVIDER: cloudflare
      TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_DNSCHALLENGE_RESOLVERS: 1.1.1.1:53,8.8.8.8:53

      # Docker
      TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: unix:///var/run/docker.sock
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_DOCKER_WATCH: true
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: proxy
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`traefik.neukoch.com`)
      traefik.http.routers.api.service: api@internal
    networks:
      - proxy
networks:
  proxy: 
    external: true